name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia meia-noite UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # para poder fazer commits no repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman contribution graph SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: rafife12

      - name: Commit and push updated SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualiza gráfico Pac-Man contribution"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
