name: Generate Pacman Contribution Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pacman-contribution-graph package
        run: npm install -g pacman-contribution-graph

      - name: Generate pacman contribution graphs
        run: |
          mkdir -p dist
          pacman-contribution-graph --username rafife12 --platform github --gameTheme github-dark --output dist/pacman-contribution-graph-dark.svg
          pacman-contribution-graph --username rafife12 --platform github --gameTheme github --output dist/pacman-contribution-graph.svg

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Atualiza Pacman Contribution Graph [skip ci]" || echo "No changes to commit"
          git push origin main
