name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 * * * *"   # executa a cada hora
  workflow_dispatch:      # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pacman Contribution Graph SVG
        uses: MartnsTech/pacman-contribution-graph@main
        with:
          user_name: rafife12
