name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Pacman Contribution Graph SVG
        uses: MartnsTech/pacman-contribution-graph@main
        with:
          user_name: rafife12

      - name: Commit and Push SVG
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dist/
          git commit -m "Update Pacman contribution graph [ci skip]" || echo "No changes to commit"
          git push
